<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>heyitsleo/NFSTools</Authors>
        <Company>NFSTools</Company>
        <Description>Plugin providing support for the YAML storage format</Description>
        <Product>Attribulator - YAML Support</Product>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <TargetFramework>net9.0</TargetFramework>
        <Version>3.0.0-dev</Version>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AsyncEnumerator" Version="4.0.2"/>
        <PackageReference Include="YamlDotNet" Version="16.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Attribulator.API\Attribulator.API.csproj"/>
    </ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)' != '' and '$(SolutionDir)' != '*Undefined*'">
        <Exec Command="if not exist $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.YAMLSupport mkdir $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.YAMLSupport" />
        <Exec Command="xcopy /Y /E $(OutDir) $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.YAMLSupport\" />
    </Target>

</Project>
