<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Authors>heyitsleo/NFSTools</Authors>
        <Company>NFSTools</Company>
        <Description>Plugin providing profiles for the Speed engine games</Description>
        <Product>Attribulator - Speed Profiles</Product>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <TargetFramework>net9.0</TargetFramework>
        <Version>3.0.0-dev</Version>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\hashes.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Resources\hashes_bin.txt" />
        <EmbeddedResource Include="Resources\hashes_bin.txt">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Attribulator.API\Attribulator.API.csproj"/>
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Core\VaultLib.Core.csproj" />
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Support.Carbon\VaultLib.Support.Carbon.csproj" />
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Support.MostWanted\VaultLib.Support.MostWanted.csproj" />
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Support.ProStreet\VaultLib.Support.ProStreet.csproj" />
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Support.Undercover\VaultLib.Support.Undercover.csproj" />
        <ProjectReference Include="..\Modules\VaultLib\VaultLib.Support.World\VaultLib.Support.World.csproj" />
    </ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(SolutionDir)' != '' and '$(SolutionDir)' != '*Undefined*'">
        <Exec Command="if not exist $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles mkdir $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles" />
        <Exec Command="xcopy /Y $(OutDir) $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles" />
        <Exec Command="if not exist $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles\Resources mkdir $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles\Resources" />
        <Exec Command="xcopy /Y Resources $(SolutionDir)Attribulator.UI\bin\$(Configuration)\net9.0-windows\plugins\Attribulator.Plugins.SpeedProfiles\Resources" />
    </Target>
</Project>
